backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_cms/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Pages"
        name: "pages"
        widget: "list"
        fields:
          - {label: "Language", name: "language", widget: "select", options: ["fr", "en"]}
          - {label: "Parent", name: "parent", widget: "relation", collection: "pages", valueField: "title", searchFields: ["title"], required: false}
          - {label: "Contenu", name: "body", widget: "markdown"}

